name: flutter_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cached_network_image: ^3.3.1
  cloud_functions: ^4.3.5
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  firebase_auth: ^4.17.4
  firebase_core: ^2.27.0
  firebase_database: ^10.4.0
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.0
  geolocator: ^10.1.1
  google_mlkit_face_detection: ^0.13.1
  http: ^1.4.0
  image: ^4.1.7
  image_picker: ^1.0.7
  latlong2: ^0.9.0
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  uuid: ^4.2.2
  video_player: ^2.10.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
